CarSell/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarSell.AppDbContext;
using CarSell.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarSell.Controllers
{
    [Authorize(Roles ="Admin,Executive")]
    public class BrandController : Controller
    {
        private readonly CarDbContext _dbContext;

        public BrandController(CarDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View(_dbContext.Brands.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Brand brand)
        {
            if(ModelState.IsValid)
            {
                _dbContext.Add(brand);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var brand = _dbContext.Brands.Find(id);
            if(brand == null)
            {
                return NotFound();
            }
            _dbContext.Brands.Remove(brand);
            _dbContext.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            var brand = _dbContext.Brands.Find(id);
            if (brand == null)
            {
                return NotFound();
            }
            return View(brand);
        }

        [HttpPost]
        public IActionResult Edit(Brand brand)
        {
            if (ModelState.IsValid)
            {
                _dbContext.Update(brand);
                _dbContext.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(brand);
        }
    }
}

CarSell/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarSell.AppDbContext;
using CarSell.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Hosting.Internal;
using cloudscribe.Pagination.Models;

namespace CarSell.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarDbContext _db;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public CarViewModel carsViewModel { get; set; }

        public CarsController(CarDbContext db, HostingEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;
            carsViewModel = new CarViewModel()
            {
                Brands = _db.Brands.ToList(),
                Models = _db.Models.ToList(),
                Car = new Models.Car()
            };
        }

        /*public IActionResult IndexOld()
        {
            //fetch dependent column based on foreign key
            var cars = _db.Cars.Include(m => m.Brand).Include(m=>m.Model);
            return View(cars.ToList());
        }*/

        public IActionResult Index(int pageSize = 3, int pageNumber=1)
        {
            //fetch dependent column based on foreign key
            int exclude = (pageSize * pageNumber) - pageSize;
            var cars = _db.Cars.Include(m => m.Brand).Include(m => m.Model)
                .Skip(exclude)
                .Take(pageSize);
            //  return View(cars.ToList());

            var pageResults = new PagedResult<Car>
            {
                Data = cars.AsNoTracking().ToList(),
                PageNumber = pageNumber,
                PageSize = pageSize,
                TotalItems = _db.Cars.Count()
            };
            return View(pageResults);
        }

        public IActionResult Create()
        {
            return View(carsViewModel);
        }

        [HttpPost, ActionName("Create")]
        public IActionResult CreatePost()
        {
            if (!ModelState.IsValid)
            {
                carsViewModel.Brands = _db.Brands.ToList();
                carsViewModel.Models = _db.Models.ToList();
                return View(carsViewModel);
            }
            _db.Cars.Add(carsViewModel.Car);
            _db.SaveChanges();

            //Get BikeID we have saved in database            
            var carID = carsViewModel.Car.Id;

            //Get wwrootPath to save the file on server
            string rootPath = _hostingEnvironment.WebRootPath;

            //Get the Uploaded files
            var files = HttpContext.Request.Form.Files;

            //Get the reference of DBSet for the bike we have saved in our database
            var savedBike = _db.Cars.Find(carID);


            //Upload the file on server and save the path in database if user have submitted file
            if (files.Count != 0)
            {

                var imagePath = @"Images\Cars\";
                //Extract the extension of submitted file
                var Extension = Path.GetExtension(files[0].FileName);

                //Create the relative image path to be saved in database table 
                var RelativeImagePath = imagePath + carID + Extension;

                //Create absolute image path to upload the physical file on server
                var AbsImagePath = Path.Combine(rootPath, RelativeImagePath);


                //Upload the file on server using Absolute Path
                using (var filestream = new FileStream(AbsImagePath, FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }

                //Set the path in database
                savedBike.ImagePath = RelativeImagePath;

                _db.SaveChanges();
            }

            return RedirectToAction(nameof(Index));
        }

        /*
        public IActionResult Edit(int id)
        {
            modelViewModel.Model = _db.Models.Include(m => m.Brand).SingleOrDefault(m => m.Id == id);
            if (modelViewModel.Model == null)
            {
                return NotFound();
            }
            return View(modelViewModel);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult EditPost()
        {
            if (!ModelState.IsValid)
            {
                return View(modelViewModel);
            }
            _db.Update(modelViewModel.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }*/

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Car car = _db.Cars.Find(id);
            if (car == null)
            {
                return NotFound();
            }
            _db.Cars.Remove(car);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

CarSell/Controllers/ModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CarSell.AppDbContext;
using CarSell.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CarSell.Controllers
{
    [Authorize(Roles = "Admin,Executive")]
    public class ModelController : Controller
    {
        private readonly CarDbContext _db;

        [BindProperty]
        public ModelViewModel modelViewModel { get; set; }

        public ModelController(CarDbContext db)
        {
            _db = db;
            modelViewModel = new ModelViewModel()
            {
                Brands = _db.Brands.ToList(),
                Model = new Models.Model()
            };
        }

        public IActionResult Index()
        {
            //fetch dependent column based on foreign key
            var model = _db.Models.Include(m => m.Brand);
            return View(model);
        }

        public IActionResult Create()
        {
            return View(modelViewModel);
        }

        [HttpPost,ActionName("Create")]
        public IActionResult CreatePost()
        {
            if(!ModelState.IsValid)
            {
                return View(modelViewModel);
            }
            _db.Models.Add(modelViewModel.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Edit(int id)
        {
            modelViewModel.Model = _db.Models.Include(m => m.Brand).SingleOrDefault(m => m.Id == id);
            if(modelViewModel.Model == null)
            {
                return NotFound();
            }
            return View(modelViewModel);
        }

        [HttpPost,ActionName("Edit")]
        public IActionResult EditPost()
        {
            if (!ModelState.IsValid)
            {
                return View(modelViewModel);
            }
            _db.Update(modelViewModel.Model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            Model model = _db.Models.Find(id);
            if(model == null)
            {
                return NotFound();
            }
            _db.Models.Remove(model);
            _db.SaveChanges();
            return RedirectToAction(nameof(Index));
        }


        [AllowAnonymous]
        [HttpGet("api/models/{brandId}")]
        public IEnumerable<Model> GetModels(int brandId)
        {
            return _db.Models.ToList().Where(m=>m.BrandFK==brandId);
        }
    }
}

CarSell/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarSell</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <a class="navbar-brand" href="#">CarSell</a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    @if (User.IsInRole("Admin") || User.IsInRole("Executive"))
                    {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-white" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Masters
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Brand" asp-action="Index">Brands</a>
                                <a class="dropdown-item" asp-controller="Model" asp-action="Index">Models</a>
                                @if (User.IsInRole("Admin"))
                                {
                                    <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Add a user</a>
                                    <a class="dropdown-item" asp-controller="Cars" asp-action="Index">Cars</a>
                                }
                            </div>
                        </li>
                    }
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CarSell - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

CarSell/Views/Shared/_OptionsPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td class="text-right">
    <div class="btn-group">
        <a type="button" class="btn btn-primary" href="@Url.Action("Edit",new { id = Model})">Edit</a>
        <form method="post" action="Delete">
            <input type="submit" onclick="if(!confirm('Are you sure you want to do delete it?')){return false}" class="btn btn-danger" asp-action="Delete" asp-route-id="@Model" value="Delete" />
        </form>
    </div>
</td>